### ISSUE TITLE
[Feature] Show sub-pages (news, info, precautions, qna)

### ISSUE THREAD

**Issue by dev-song** [ddusi/covid19_WordCloud#18]
Main(home) 페이지와 동일하게, Django template 기반으로
보조 페이지들을 구현하고자 합니다.

보조 페이지 목록은 다음과 같습니다.
- News
- Info
- Precautions
- QnA

---
### 참고
프로토타입은 Precautions와 QnA가 합쳐져 있고 Status가 추가적으로 존재하나,
기존 프로젝트 백엔드 단에서의 라우팅이 분리되어 있는 상황이므로
우선은 각각의 URL을 따라 별도의 페이지로 구현할 예정입니다.

precautions와 qna를 합치고 status 페이지를 추가로 표현하는 것은 추후 별도의 새로운 이슈로 만들어 진행하겠습니다.

**Comment by dev-song** [comment]
Precautions와 QnA 페이지 구조가 합쳐짐에 따라, News & Info 페이지만 구현한 뒤 이슈 종료합니다.

**Comment by chrisjo-dev** [comment]
오,, 고생하셨습니다!
