### ISSUE TITLE
Change precautions content with English text

### ISSUE THREAD

**Issue by dev-song** [ddusi/covid19_WordCloud#53]
## Goal
- Switch precautions text with English text (currently it's written in Korean)

## Reference
[Google search result about COVID-19 Precautions](https://www.google.com/search?rlz=1C5CHFA_enKR906KR906&sxsrf=ALeKk03U3erUtcELyHKYrkqygAJC44yd3w:1598434292483&ei=9CtGX6OJHYWkmAXptZKABQ&q=covid-19+Precautions&oq=covid-19+Precautions&gs_lcp=CgZwc3ktYWIQAzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BwgjELADECc6BwgAELADEENQ3WBY3WBg3mVoAXAAeACAAZIBiAGSAZIBAzAuMZgBAKABAqABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwij08zhx7jrAhUFEqYKHemaBFAQ4dUDCA0&uact=5&safe=images)

**Comment by chrisjo-dev** [comment]
원문이 있었네요!

**Comment by dev-song** [comment]
네ㅎㅎ 구글 검색결과 언어설정만 바꾸면됩니다
