### ISSUE TITLE
Prototype front view

### ISSUE THREAD

**Issue by chrisjo-dev** [ddusi/covid19_WordCloud#7]
<br><br><br><br>
## 간단한 페이지 뷰 디자인
1. home
![01_Home](https://user-images.githubusercontent.com/58924238/96447583-1344f480-124d-11eb-8fba-a057e7364aca.jpg)
2. news
![02_News](https://user-images.githubusercontent.com/58924238/96447592-18a23f00-124d-11eb-9674-b22da4ca57aa.jpg)
3. info
![03_info](https://user-images.githubusercontent.com/58924238/96447594-19d36c00-124d-11eb-9774-2b6c37b4f6e6.jpg)
4. precautions
![04_Precautions](https://user-images.githubusercontent.com/58924238/96447596-1b049900-124d-11eb-87ee-a79112faef63.jpg)
5. status
![05_Status](https://user-images.githubusercontent.com/58924238/96447602-1c35c600-124d-11eb-81ee-869145ce70fd.jpg)

<br><br><br><br>

## 참고 시안
![bootstrap-forum-template-145-768x636](https://user-images.githubusercontent.com/58924238/96447713-4e472800-124d-11eb-8b0f-fe1dd281c784.jpg)
![cover](https://user-images.githubusercontent.com/58924238/96447806-7171d780-124d-11eb-82ab-91bec69da700.png)
https://getbootstrap.com/docs/4.5/examples/cover/
![image](https://user-images.githubusercontent.com/58924238/96447935-a41bd000-124d-11eb-9f1e-cf49748968e3.png)

**Comment by dev-song** [comment]
추후 편한 접근을 위해 참고 시안에 표시된 사이트 링크 기재합니다.
- [OneSocial Forums](https://demos.buddyboss.com/onesocial/forums/)
- [Cover Page - bootstrap](https://getbootstrap.com/docs/4.5/examples/cover/)
- [Front Dashboard - bootstrap](https://themes.getbootstrap.com/product/front-admin-dashboard-template/)

**Comment by chrisjo-dev** [comment]
참고로 디자인 툴은 카카오의 `오븐`이라는 툴을 사용하였습니다. 
[오븐 바로가기](https://ovenapp.io/)
오븐에도 초대기능이 있네요. 저 디자인 수정 원하시면 초대해드리겠습니다!

**Comment by dev-song** [comment]
와이어프레임 디자인 관련해서 위키에 정리해놨습니다.
[위키 링크](https://github.com/ddusi/covid19_WordCloud/wiki/%5BFront%5D-%EC%99%80%EC%9D%B4%EC%96%B4%ED%94%84%EB%A0%88%EC%9E%84-%EC%9E%91%EC%97%85%EA%B3%B5%EA%B0%84-%EB%B0%8F-%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C)

카카오 오븐은 이따가 한 번 써보겠습니다ㅎㅎ
다른 디자이너나 프론트엔드 분들은 Figma나 Adobe XD, Zeplin 등을 많이 쓰시는 것 같더라구요.

**Comment by chrisjo-dev** [comment]
이건 대외비이긴 한데 한번 참고 해보셔요! 
[피그마](https://www.figma.com/file/1x7ndHRU74OJgNj0ooAPiL/%ED%98%BC%EC%A1%B1%EC%9D%98-%EC%A0%9C%EC%99%95?node-id=0%3A1)

**Comment by chrisjo-dev** [comment]
## page 기능 상세표
- Home
  메인화면으로 웰컴 메세지, 최신 뉴스, 시각화 자료를 배치한다. 중앙에 버튼 두개가 있으며, `news`를 누르면 최신 뉴스가 있는 News페이지로 넘어간다. `more`을 누르면 Status 페이지로 넘어간다.

- News
  최신뉴스들을 board형식으로 크롤링해 와서 뿌린다. 여기서 중요한 것은 왼쪽에는 최신 뉴스들을 분석해 Word_Cloud를 뿌려준다.

- Info
  코로나에 관련된 기본 정보들을 알려주는 페이지이다. ( 디자인 고민을 더 해봐야 함. )

- Precautions - QnA
  예방방법과 간단한 질문을 남길 수 있는 페이지. ( 여기도 디자인 고민을 해야함. )
  
- Status
  우리 페이지의 핵심기능이다. 코로나에 관련된 시각화 자료를 관리자 페이지 느낌처럼 정보를 제공한다. 오른쪽 상단의 버튼 기능은 다크/화이트 모드 혹은 다른 시각화자료 뿌려주는걸 고민중이다.


## 참고사항
아무래도 코로나 관련된 페이지이다 보니까 조금 격식이 있는 디자인을 선호합니다.  컬러도 밝은 컬러보다 어두운 계열

**Comment by dev-song** [comment]
## 초기 레이아웃 와이어프레임
1. Landing Page
![Landing Page](https://user-images.githubusercontent.com/52951039/96739448-c1da6800-13fa-11eb-91a4-3dfebca5940b.png)
2. News Page
![image](https://user-images.githubusercontent.com/52951039/96739494-cc94fd00-13fa-11eb-9bed-c1213180f80f.png)
3. Info Page
![image](https://user-images.githubusercontent.com/52951039/96739509-d1f24780-13fa-11eb-85a0-b731812b9bb5.png)
- 내부 Container 표시 방식: 화살표 버튼을 눌러 화면 안의 내용이 전환되는 방식
  - 즉, viewport height는 고정
4. Precautions Page
![image](https://user-images.githubusercontent.com/52951039/96739528-d74f9200-13fa-11eb-9a6c-47acfc44d6b9.png)
- Precautions 섹션은 3~4초마다 예방법 Auto-rotation되도록 구현
  - 하단 <, > 버튼 눌러도 전환 가능
- 질문 길이 제한할 거라면 질문 섹션과 Q&A 섹션 위치 서로 바꾸는 것도 고려
5. Status Page (Main)
![image](https://user-images.githubusercontent.com/52951039/96739551-ddde0980-13fa-11eb-8214-10e96f84f58e.png)
- 차트 종류에 따라 레이아웃 변화
  - 소형 차트가 여럿 모여 의미 있는 데이터를 표현할 경우, 한 페이지에 연관성 있게 배치 (차트 유형은 데이터 형태에 맞는 것으로 유연하게 선택)
  - 하나의 대형 차트/지도로 표현하는 경우, 한 페이지에 하나의 차트/지도를 통으로 할당
6. Status Page (Sub - additional chart/map)
![image](https://user-images.githubusercontent.com/52951039/96739580-e6364480-13fa-11eb-9278-88da320fa173.png)

**Comment by dev-song** [comment]
추가 고민 필요
---
- 색상 조합
- GNB fixed 여부 결정
  - 사용자의 viewport height가 작아 현재 레이아웃도 상하로 짤릴 때, 스크롤을 내릴 경우 GNB를 계속 보여줄 지, 가릴 지

**Comment by chrisjo-dev** [comment]
GNB가 page header를 뜻하는것 같네요! 
고정이 필요할것 같습니다!

**Comment by chrisjo-dev** [comment]
레이아웃 협의가 끝났으므로 close 합니다.
