### ISSUE TITLE
[Feature] Show main page

### ISSUE THREAD

**Issue by dev-song** [ddusi/covid19_WordCloud#9]
기존 Django 프레임워크 위에 웹어플리케이션을 띄우려고 합니다.
우선 React를 사용해 시도할 예정입니다.

**Comment by chrisjo-dev** [comment]
좋습니다! 저도 리액트좀 공부해야겠네요!

**Comment by dev-song** [comment]
10/23 오프라인 미팅 결과, React가 아닌 HTML/CSS/바닐라 JS 기반 레이아웃 작업으로 결정
데이터는 API가 아닌 서버 내 파일에 직접 접근해 View에 표시하게 됨

→ 이에 따라 테스팅용으로 생성했던 브랜치 feature/front_main_page는 삭제 & 새 브랜치로 다시 생성 후 작업 예정

**Comment by dev-song** [comment]
@ddusi 홈 화면 django template inheritance 기능 활용해 이식했습니다.
이렇게 PR한 뒤 이상 없으면 merge하는 게 맞나요? 한 번 확인 부탁드립니다ㅎㅎ

**Comment by chrisjo-dev** [comment]
넵 수업 이제 끝났네요 ㅠㅠ 집에가서 확인해보겠습다

**Comment by dev-song** [comment]
merge 완료 👍 
이슈 닫습니다.
